### ISSUE TITLE
Контрольна робота 1

### ISSUE THREAD

**Issue by baka314** [oleksandrblazhko/ai-212-zelinska#7]
Завдання 1
Обрана потреба: Комфортний сон

Інформаційні умови:

Доступ до інформації про здоровий сон: інформація про режим сну, тривалість сну, правильне положення тіла під час сну, фактори, які можуть перешкоджати сну, тощо.
Доступ до засобів для забезпечення комфортного сну: зручне ліжко, подушки, матрац, ковдри, тощо.
Обґрунтування вибору:

Доступ до інформації про здоровий сон дозволяє людям зрозуміти, як забезпечити собі здоровий та комфортний сон.
Доступ до засобів для забезпечення комфортного сну дозволяє людям створити для себе сприятливі умови для сну.

Завдання 2

Пригадайте мету вашого програмного продукту, створену у лабораторній роботі No1,
вказавши її у відповіді;

обґрунтуйте для трьох прецедентів той факт, що результати їх роботи дійсно наближають
користувача вашого програмного продукту до досягнення вказаної раніше мети.

1)

Мета програмного продукту полягає в тому, щоб забезпечити інтерес до скульптури та безпеку на роботі, враховуючи потребу у дружбі та комфорту сну.

2)

Прецедент 1: Отримання заспокійливого контенту

Цей прецедент наближає користувача до досягнення мети програмного продукту, оскільки він допомагає користувачам отримати комфортний сон. Комфортний сон є важливою умовою для загального здоров'я та добробуту, включаючи здатність до концентрації, навчання та творчості. Заспокійливий контент може допомогти користувачам розслабитися та заснути, що може призвести до поліпшення якості їхнього сну.

Прецедент 2: Створити нову скульптуру

Цей прецедент наближає користувача до досягнення мети програмного продукту, оскільки він допомагає користувачам розвивати свій інтерес до скульптури. Скульптура - це творчий вид мистецтва, який може бути корисним для розвитку візуального мислення, просторової уяви та координації рухів. Створення нової скульптури може допомогти користувачам розкрити свій творчий потенціал і отримати задоволення від процесу створення.

Прецедент 3: Пошук користувача для спілкування

Цей прецедент наближає користувача до досягнення мети програмного продукту, оскільки він допомагає користувачам підтримувати соціальні зв'язки. Соціальні зв'язки важливі для загального здоров'я та добробуту, включаючи здатність до стресостійкості та благополуччя. Спілкування з іншими людьми може допомогти користувачам відчути себе пов'язаними з іншими та відчути підтримку.

Ось більш детальне обґрунтування кожного прецеденту:

Прецедент 1: Отримання заспокійливого контенту

Комфортний сон є важливою умовою для загального здоров'я та добробуту. Він може допомогти користувачам:

Покращити концентрацію та увагу
Підвищити здатність до навчання
Знизити стрес та занепокоєння
Покращити настрій
Зміцнити імунну систему
Заспокійливий контент, такий як музика, звуки природи або медитативні практики, може допомогти користувачам розслабитися та заснути. Це може призвести до поліпшення якості їхнього сну, що може призвести до таких переваг, як:

Збільшення енергії
Покращення настрою
Зниження ризику хронічних захворювань
Прецедент 2: Створити нову скульптуру

Скульптура - це творчий вид мистецтва, який може бути корисним для розвитку таких навичок, як:

Візуальне мислення
Просторова уява
Координація рухів
Створення нової скульптури може допомогти користувачам:

Розкрити свій творчий потенціал
Отримати задоволення від процесу створення
Навчитися новим навичкам
Скульптура також може бути способом самовираження та спілкування з іншими. Вона може допомогти користувачам:

Поділитися своїми ідеями та почуттями
Побудувати зв'язки з іншими
Створити щось цінне
Прецедент 3: Пошук користувача для спілкування

Соціальні зв'язки важливі для загального здоров'я та добробуту. Вони можуть допомогти користувачам:

Відчувати себе пов'язаними з іншими
Отримати підтримку
Знизити стрес
Покращити настрій
Пошук користувача для спілкування може допомогти користувачам:

Знайти друзів та однодумців
Побудувати нові стосунки
Підтримувати зв'язок з іншими

**Comment by oleksandrblazhko** [comment]
Рішення розглянемо на останньому занятті з лабораторної роботи, 
на останній лекції або на консультації.

**Comment by oleksandrblazhko** [comment]
2 бали
